name: cloudmusic
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  sprintf: "^4.0.0"
  dio: ^1.0.9
  cached_network_image: ^0.8.0
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.2
  shared_preferences: ^0.5.3+1
  video_player: ^0.10.1+3
  transparent_image: ^1.0.0
  audioplayer: ^0.5.2
  share: ^0.6.1
  intl: ^0.15.8
  common_utils: ^1.1.1
  chewie: ^0.9.7
  fish_redux: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ic_3bar.png
    - images/ic_addmoon_w.png
    - images/ic_ball_w.png
    - images/ic_barheart_w.png
    - images/ic_calendar.png
    - images/ic_car_w.png
    - images/ic_circlemuscib_b.png
    - images/ic_disc_blackground.png
    - images/ic_disc.png
    - images/ic_ice_w.png
    - images/ic_jazz_w.png
    - images/ic_fm_w.png
    - images/ic_kidchannel_w.png
    - images/ic_mainmusic.png
    - images/ic_mainradio.png
    - images/ic_mainrman.png
    - images/ic_needle.png
    - images/ic_piano_w.png
    - images/ic_runman_w.png
    - images/ic_mic_b.png
    - images/CacheBG.jpg
    - images/circlewave.json
    - images/ic_playwbar_b.png
    - images/ic_circlemuscib_b.png
    - images/ic_musicb_b.png
    - images/ic_userwstar_b.png
    - images/ic_moon.png
    - images/ic_mic2_b.png
    - images/ic_clock2.png
    - images/ic_clock.png
    - images/ic_scan_b.png
    - images/ic_setting_b.png
    - images/ic_ticket.png
    - images/ic_box_b.png
    - images/ic_music_cb.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
